on:
    workflow_call:
      secrets:
        GH_TOKEN:
          required: true
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
  
      inputs:
        CIDR:
          type: string
          required: true
        IMAGE:
          type: string
          required: true
        AWS_REGION:
          type: string
          required: true
  
jobs:
    create-ecs-environment:
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.AWS_REGION }}
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Install dependencies
          run: |
            cd Infrastructure/ecs-django-app 
            npm install
            npm install -g aws-cdk
        - name: Deploy the project
          env:
            CIDR: ${{ inputs.CIDR }}
            IMAGE: ${{ inputs.IMAGE }}
          run: |
            cd Infrastructure/ecs-django-app
            cdk synth
            cdk deploy --require-approval never
